import Card from "@/components/Card";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

interface Pokemon {
  name: string;
  url: string;
}

interface PokemonArray {
  results: Pokemon[];
}

export async function getServerSideProps() {
  const res = await fetch(
    "https://pokeapi.co/api/v2/pokemon?limit=24&offset=0"
  );
  const data: PokemonArray = await res.json();

  return {
    props: {
      pokemon: data,
    },
  };
}

export default function Home({ pokemon }: { pokemon: PokemonArray }) {
  const [pokemonList, setPokemonList] = useState<Pokemon[]>(pokemon.results);
  const [limit, setLimit] = useState(20);

  const handleSeeMoreClick = async () => {
    const res = await fetch(
      `https://pokeapi.co/api/v2/pokemon?limit=8&offset=${limit}`
    );
    const data: PokemonArray = await res.json();
    setLimit((prevLimit) => prevLimit + 8);
    setPokemonList((prevPokemonList) => prevPokemonList.concat(data.results));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col justify-center">
          <div className="flex justify-center">
            <div className="flex flex-wrap justify-center w-[1440px]">
              {pokemonList?.length === 0 ? (
                <div>Loading...</div>
              ) : (
                pokemonList?.map((pokemon) => (
                  <Card key={pokemon.name} pokemon={pokemon} />
                ))
              )}
            </div>
          </div>
          <button
            className="bg-blue-300 w-[150px] m-auto mb-5"
            onClick={handleSeeMoreClick}
          >
            See more.
          </button>
        </div>
      </main>
    </>
  );
}
