import Card from "@/components/Card";
import Head from "next/head";
import { useState } from "react";

interface Pokemon {
  name: string;
  url: string;
}

interface PokemonArray {
  results: Pokemon[];
}

export async function getServerSideProps() {
  const res = await fetch(
    "https://pokeapi.co/api/v2/pokemon?limit=24&offset=0"
  );
  const data: PokemonArray = await res.json();

  return {
    props: {
      pokemon: data,
    },
  };
}

export default function Home({ pokemon }: { pokemon: PokemonArray }) {
  const [pokemonList, setPokemonList] = useState<Pokemon[]>(pokemon.results);
  const [limit, setLimit] = useState(pokemon.results.length);

  const handleSeeMoreClick = async () => {
    const res = await fetch(
      `https://pokeapi.co/api/v2/pokemon?limit=24&offset=${limit}`
    );
    const data: PokemonArray = await res.json();
    setLimit((prevLimit) => prevLimit + 24);
    setPokemonList((prevPokemonList) => prevPokemonList.concat(data.results));
  };
  return (
    <>
      <Head>
        <title>PokeList</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-center">
        <h1 className="pokefont text-6xl my-8 md:text-8xl">PokeList</h1>
        <div className="flex flex-col justify-center">
          <div className="flex justify-center">
            <div className="flex flex-wrap justify-center w-[1440px]">
              {pokemonList?.length === 0 ? (
                <div>Loading...</div>
              ) : (
                pokemonList?.map((pokemon) => (
                  <Card key={pokemon.name} pokemon={pokemon} />
                ))
              )}
            </div>
          </div>
          <button
            className="bg-green-600 text-white px-3 py-2 m-auto my-5 rounded-md text text-lg font-semibold"
            onClick={handleSeeMoreClick}
          >
            See more
          </button>
        </div>
      </main>
    </>
  );
}
